# Generated by Django 4.2.7 on 2026-04-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CardProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("job_title", models.CharField(blank=True, max_length=150)),
                ("location", models.CharField(blank=True, max_length=150)),
                ("about", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="photos/"),
                ),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=100)),
                ("website", models.URLField(blank=True)),
                ("whatsapp", models.CharField(blank=True, max_length=20)),
                ("telegram", models.CharField(blank=True, max_length=50)),
                ("viber", models.CharField(blank=True, max_length=20)),
                ("facebook", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                ("twitter", models.URLField(blank=True)),
                ("tiktok", models.URLField(blank=True)),
                ("youtube", models.URLField(blank=True)),
                ("discord", models.CharField(blank=True, max_length=50)),
                ("linkedin", models.URLField(blank=True)),
                ("github", models.URLField(blank=True)),
                ("behance", models.URLField(blank=True)),
                ("dribbble", models.URLField(blank=True)),
                ("skills_text", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Card Profile",
            },
        ),
    ]
